# General
snippet DOCKERNODE "Docker file for node." A
## Build layer
FROM node:16.0.0 AS builder 
WORKDIR /app
COPY . .
RUN npm ci --only=production

## Production layer
FROM alpine
WORKDIR /app
COPY --from=builder /app .
RUN apk add --update nodejs
RUN addgroup -S app && adduser -S prod -G app
USER prod
CMD ["node", "index.js"]
endsnippet
