#!/bin/bash

if [ ! -d "$1/dev/microsoft"]; then
  mkdir -p "$1/dev/microsoft"
fi

mkdir -p ~/dev/microsoft
git clone https://github.com/microsoft/vscode-node-debug2.git ~/dev/microsoft/vscode-node-debug2
cd ~/dev/microsoft/vscode-node-debug2
npm install 
npm run build
