#!/bin/bash
if [[ $OSTYPE = darwin*  ]]; then
  "We don't know how to do this on a Mac yet!"
else
  if [[ "$1" == 'true' ]]; then
    xdotool getactivewindow keydown ctrl key 20 key 20 key 20 key 20 key 20 key 20 keyup ctrl
    xdotool getactivewindow keydown ctrl key l key l keyup ctrl
    xdotool key ctrl
  else
    xdotool getactivewindow keydown ctrl key 21 key 21 key 21 key 21 key 21 key 21 keyup ctrl
    xdotool getactivewindow keydown ctrl key l key l keyup ctrl
    xdotool key ctrl
  fi
fi
