#!/bin/bash

snapshot_time="${1}"
config_path="${2}"

if [[ $(uname) == "Darwin" ]]; then
  $NVIM --version > "$config_path/lockfiles/mac/nvim_snapshots/$snapshot_time"
else
  $NVIM --version > "$config_path/lockfiles/linux/nvim_snapshots/$snapshot_time"
fi
