#!/bin/bash

snapshot_time="${1}"

if [[ "$OSTYPE" == "darwin"* ]]; then
  nvim --version > "./lockfiles/mac/nvim_snapshots/$snapshot_time"
else
  nvim --version > "./lockfiles/linux/nvim_snapshots/$snapshot_time"
fi
